version: 2
jobs:
  test:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      # Restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}

      # Install npm dependencies and Cypress binary
      # If they were cached, this step is super quick
      - run:
          name: Install dependencies
          command: npm ci

      # Save npm dependencies and Cypress binary for future runs
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # Running Eslint before kick starting the testing
      - run:
          name: Running ESlint
          command: npm run lint-check

      # Running the tests
      - run: 
          name: Run Tests and Save report
          command: npx cypress run --env username=${USERNAME},password=${PASSWORD},username1=${USERNAME1},username2=${USERNAME2},username3=${USERNAME3} —-reporter mochawesome

      # Generating the JSON report
      - run:
          name: Generate reports
          command: npm run merge-reports

      # Converting the JSON to HTML    
      - run:
          name: Convert JSON to HTML report file
          command: npm run create-report
      
      # Upload test coverage as artifact 
      - store_artifacts: 
          path: mochawesome-report

workflows:
  version: 2
  build:
    jobs:
      - test
