version: 2
jobs:
  test:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      # restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      # install npm dependencies and Cypress binary
      # if they were cached, this step is super quick
      - run:
          name: Install dependencies
          command: npm ci
      # save npm dependencies and Cypress binary for future runs
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: 
          name: Run Tests and Save report
          command: npx cypress run --env username=${USERNAME},password=${PASSWORD},username1=${USERNAME1},username2=${USERNAME2},username3=${USERNAME3} —-reporter mochawesome
      - run:
          name: Generate reports
          command: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
      - run:
          name: Convert JSON to HTML report file
          command: npx mochawesome-report-generator mochawesome.json
      
      # upload test coverage as artifact 
      - store_artifacts: 
          path: mochawesome-report

workflows:
  version: 2
  build:
    jobs:
      - test
